apiVersion: v1
entries:
  azure-service-operator:
  - apiVersion: v2
    created: "2023-04-14T20:21:41.56678625Z"
    description: Deploy components and dependencies of azure-service-operator
    digest: d344651f48b66d08fb791f10e309743c4e5cfa520080d59875054e4ef18481b9
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0.tgz
    version: v2.0.0
  - apiVersion: v2
    created: "2023-04-14T20:21:41.565545938Z"
    dependencies:
    - condition: installCRDs
      name: azure-service-operator-crds
      repository: ""
      version: v2.0.0-beta.5
    description: Deploy components and dependencies of azure-service-operator
    digest: 2c9d5788c23914d1308613a1d0e78bd8ea0e77b5853a337cfbe56ff0fc9de977
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.5.tgz
    version: v2.0.0-beta.5
  - apiVersion: v2
    created: "2023-04-14T20:21:41.534476943Z"
    dependencies:
    - condition: installCRDs
      name: azure-service-operator-crds
      repository: ""
      version: v2.0.0-beta.4
    description: Deploy components and dependencies of azure-service-operator
    digest: acc0c88e6812a96b996c977e23d771d2d7303abd20a2bb5a85842508d4c6d4c7
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.4.tgz
    version: v2.0.0-beta.4
  - apiVersion: v2
    created: "2023-04-14T20:21:41.502511739Z"
    dependencies:
    - condition: installCRDs
      name: azure-service-operator-crds
      repository: ""
      version: v2.0.0-beta.3
    description: Deploy components and dependencies of azure-service-operator
    digest: 51ae0842a96c86f3999455d5b4ca7a81b1e39b5b9c78ad078d82e628699b7bbe
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.3.tgz
    version: v2.0.0-beta.3
  - apiVersion: v2
    created: "2023-04-14T20:21:41.473351462Z"
    dependencies:
    - condition: installCRDs
      name: azure-service-operator-crds
      repository: ""
      version: v2.0.0-beta.2
    description: Deploy components and dependencies of azure-service-operator
    digest: 13b4b6f943860ef241ff735cd2717af0b4b98454cd6f95315006e2ae60060a79
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.2.tgz
    version: v2.0.0-beta.2
  - apiVersion: v2
    created: "2023-04-14T20:21:41.445591199Z"
    dependencies:
    - condition: installCRDs
      name: azure-service-operator-crds
      repository: ""
      version: v2.0.0-beta.1
    description: Deploy components and dependencies of azure-service-operator
    digest: 70275156e4dea3fba2847481930bb255e051090edd4d11d57812534be70b099b
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.1.tgz
    version: v2.0.0-beta.1
  - apiVersion: v2
    created: "2023-04-14T20:21:41.418666843Z"
    dependencies:
    - condition: installCRDs
      name: azure-service-operator-crds
      repository: ""
      version: v2.0.0-alpha.6
    description: Deploy components and dependencies of azure-service-operator
    digest: 46d98178fcc807204382b156bf1310b101e0ac9defefc3654e11b976e11a550a
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.0.tgz
    version: v2.0.0-beta.0
  - apiVersion: v2
    created: "2023-04-14T20:21:41.393319002Z"
    description: Deploy components and dependencies of azure-service-operator
    digest: 644b1f9e38f7cd868963e52dc449cbb16231c10b3ee0ba303e864f1a392444fb
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-alpha.6.tgz
    version: v2.0.0-alpha.6
  azure-service-operator-crds:
  - apiVersion: v2
    created: "2023-04-14T20:21:41.380584181Z"
    description: Install Custom Resources for Azure Service Operator v2
    digest: 0688cc7a208fad130b74e4b3e0063e52079ff9ec560dd2c73378e08b88f19838
    name: azure-service-operator-crds
    urls:
    - azure-service-operator-crds-v2.0.0-beta.5.tgz
    version: v2.0.0-beta.5
  - apiVersion: v2
    created: "2023-04-14T20:21:41.350589396Z"
    description: Install Custom Resources for Azure Service Operator v2
    digest: 2deca49130ff58d3c550dc8be1d727ecafbf80d2492a9df3c2220f3a03d92b76
    name: azure-service-operator-crds
    urls:
    - azure-service-operator-crds-v2.0.0-beta.4.tgz
    version: v2.0.0-beta.4
  - apiVersion: v2
    created: "2023-04-14T20:21:41.320046006Z"
    description: Install Custom Resources for Azure Service Operator v2
    digest: 5feb153b1020a3636914db3e98e316b8cb29f2d7df7bba7282124e186ee323c2
    name: azure-service-operator-crds
    urls:
    - azure-service-operator-crds-v2.0.0-beta.3.tgz
    version: v2.0.0-beta.3
  - apiVersion: v2
    created: "2023-04-14T20:21:41.292491044Z"
    description: Install Custom Resources for Azure Service Operator v2
    digest: 8f38f08e53bae760fdf34129af116e1587396e061a1c97c54845c6fe42b1e349
    name: azure-service-operator-crds
    urls:
    - azure-service-operator-crds-v2.0.0-beta.2.tgz
    version: v2.0.0-beta.2
  - apiVersion: v2
    created: "2023-04-14T20:21:41.264256376Z"
    description: Install Custom Resources for Azure Service Operator v2
    digest: afc2b2b4d46b92ec0f0a23aee7864fa6e7fea59c4aed3cc91528e57da5fb9374
    name: azure-service-operator-crds
    urls:
    - azure-service-operator-crds-v2.0.0-beta.1.tgz
    version: v2.0.0-beta.1
  - apiVersion: v2
    created: "2023-04-14T20:21:41.237580822Z"
    description: Install Custom Resources for Azure Service Operator v2
    digest: 7578c1a1f32301d906ad5b09abd627b0e82ea4dde2b51d7fdf04bc21fe1e8643
    name: azure-service-operator-crds
    urls:
    - azure-service-operator-crds-v2.0.0-beta.0.tgz
    version: v2.0.0-beta.0
generated: "2023-04-14T20:21:41.214448402Z"
