apiVersion: authorization.azure.com/v1alpha1api20200801preview
kind: RoleAssignment
metadata:
  name: aso-sample-roleassignment
  namespace: default
spec:
  location: westcentralus
  # This resource can be owner by any resource. In this example we've chosen a resource group for simplicity
  owner:
    name: aso-sample-rg
    group: microsoft.resources
    kind: ResourceGroup
  # This is the Principal ID of the AAD identity to which the role will be assigned
  principalId: 00000000-0000-0000-0000-000000000000
  roleDefinitionReference:
    # This ARM ID represents "Contributor" - you can read about other built in roles here: https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles
    armId: /subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c

