{{- if or (eq .Values.multiTenant.enable false) (eq .Values.multiTenant.isCluster true) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azureserviceoperator-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: azureserviceoperator-proxy-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{.Release.Namespace}}
{{- end }}
