apiVersion: network.azure.com/v1alpha1api20201101
kind: VirtualNetwork
metadata:
  name: samplevnet
  namespace: default
spec:
  location: westcentralus
  owner:
    name: aso-sample-rg
  addressSpace:
    addressPrefixes:
      - 10.0.0.0/16
