apiVersion: v1
kind: Secret
metadata:
  name: manager-bootstrap-credentials
  namespace: system
type: Opaque
data:
  subscription-id: ${AZURE_SUBSCRIPTION_ID_B64}
  tenant-id: ${AZURE_TENANT_ID_B64}
  client-id: ${AZURE_CLIENT_ID_B64}
  client-secret: ${AZURE_CLIENT_SECRET_B64}