apiVersion: keyvault.azure.com/v1beta20210401preview
kind: Vault
metadata:
  name: samplevaul
  namespace: default
spec:
  location: westcentralus
  owner:
    name: aso-sample-rg
  properties:
    tenantId: "1C793267-c310-d4ae-7BD5-5Af5BEF875D3"
    sku:
      family: A
      name: standard
    accessPolicies:
      - applicationId: "1C793267-c310-d4ae-7BD5-5Af5BEF875D3"
        objectId: "1C793267-c310-d4ae-7BD5-5Af5BEF875D3"
        tenantId: "1C793267-c310-d4ae-7BD5-5Af5BEF875D3"
        permissions:
          certificates:
            - "get"
          keys:
            - "get"
          secrets:
            - "get"
          storage:
            - "get"