apiVersion: dbforpostgresql.azure.com/v1api20250801
kind: FlexibleServersAdvancedThreatProtectionSettings
metadata:
  name: advancedprotection
  namespace: default
spec:
  owner:
    name: asosampleserver20250801
  state: Enabled
