apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.5
  creationTimestamp: null
  name: virtualnetworks.azure.microsoft.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.provisioned
    name: Provisioned
    type: string
  - JSONPath: .status.message
    name: Message
    type: string
  group: azure.microsoft.com
  names:
    kind: VirtualNetwork
    listKind: VirtualNetworkList
    plural: virtualnetworks
    shortNames:
    - vn
    singular: virtualnetwork
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: VirtualNetwork is the Schema for the virtualnetworks API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: VirtualNetworkSpec defines the desired state of VirtualNetwork
          properties:
            addressSpace:
              type: string
            location:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster Important: Run "make" to regenerate code after modifying this file'
              type: string
            resourceGroup:
              pattern: ^[-\w\._\(\)]+$
              type: string
            subnets:
              items:
                description: VNetSubnets defines subnets for this vnet
                properties:
                  serviceEndpoints:
                    items:
                      type: string
                    type: array
                  subnetAddressPrefix:
                    type: string
                  subnetName:
                    description: 'INSERT ADDITIONAL STATUS FIELD - define observed state of cluster Important: Run "make" to regenerate code after modifying this file'
                    type: string
                required:
                - subnetAddressPrefix
                - subnetName
                type: object
              type: array
          required:
          - addressSpace
          - location
          - resourceGroup
          type: object
        status:
          description: ASOStatus (AzureServiceOperatorsStatus) defines the observed state of resource actions
          properties:
            completed:
              format: date-time
              type: string
            containsUpdate:
              type: boolean
            failedProvisioning:
              type: boolean
            flattenedSecrets:
              type: boolean
            message:
              type: string
            output:
              type: string
            pollingUrl:
              type: string
            provisioned:
              type: boolean
            provisioning:
              type: boolean
            requested:
              format: date-time
              type: string
            resourceId:
              type: string
            specHash:
              type: string
            state:
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
