apiVersion: web.azure.com/v1beta20220301
kind: Site
metadata:
  name: aso-sample-function
  namespace: default
spec:
  enabled: true
  location: westus2
  owner:
    name: aso-sample-rg
  serverFarmReference:
    group: web.azure.com
    kind: Serverfarm
    name: aso-sample-appservice
