apiVersion: dbformariadb.azure.com/v1api20180601
kind: Configuration
metadata:
  name: query_cache_size
  namespace: default
  annotations: 
    # Can't be directly deleted in Azure, only by deleting the parent server
    # We can delete it from the cluster by applying this annotation, but this won't change anything in Azure.
    serviceoperator.azure.com/reconcile-policy: detach-on-delete
spec:
  azureName: query_cache_size
  owner:
    name: myserver
  value: "102400"
