apiVersion: dbforpostgresql.azure.com/v1api20220120preview
kind: FlexibleServersConfiguration
metadata:
  name: pgaudit
  namespace: default
  annotations: 
    # Can't be directly deleted in Azure, only by deleting the parent server
    # We can delete it from the cluster by applying this annotation, but this won't change anything in Azure.
    serviceoperator.azure.com/reconcile-policy: detach-on-delete
spec:
  owner:
    name: samplepostgresql
  azureName: pgaudit.log
  source: user-override
  value: READ
