apiVersion: azure.microsoft.com/v1alpha1
kind: PostgreSQLServer
metadata:
  name: postgresqlserver-sample
spec:
  location: southcentralus
  resourceGroup: resourcegroup-azure-operators
  serverVersion: "10"
  sslEnforcement: Enabled
  sku:
    name: B_Gen5_2
    tier: Basic
    family: Gen5
    size: "51200"
    capacity: 2
  # Use the field below to optionally specify a different keyvault 
  # to store the server admin credential secrets in
  #keyVaultToStoreSecrets: asoSecretKeyVault
---
apiVersion: azure.microsoft.com/v1alpha1
kind: PostgreSQLDatabase
metadata:
  name: postgresqldatabase-sample
spec:
  resourceGroup: resourcegroup-azure-operators
  server: postgresqlserver-sample
---
apiVersion: azure.microsoft.com/v1alpha1
kind: PostgreSQLFirewallRule
metadata:
  name: postgresqlfirewallrule-sample
spec:
  resourceGroup: resourcegroup-azure-operators
  server: postgresqlserver-sample
  startIpAddress: 0.0.0.0
  endIpAddress: 0.0.0.0
