apiVersion: azure.microsoft.com/v1alpha1
kind: MySQLServer
metadata:
  name: mysqlserver-sample
spec:  
  location: eastus2
  resourceGroup: resourcegroup-azure-operatpr
  serverVersion: "8.0"
  sslEnforcement: Enabled
  sku:
    name: B_Gen5_2
    tier: Basic
    family: Gen5
    size: "51200"
    capacity: 2