apiVersion: azure.microsoft.com/v1
kind: Eventhub
metadata:
  name: eventhub-sample-2307-09
spec:
  location: "westus"
  resourcegroup: "resourcegroup-sample-1907"
  namespace: "eventhubnamespace-sample-6"
  properties:
    messageretentionindays: 7
    partitioncount: 1
  authorizationrule:
    name : "RootManageSharedAccessKey"
    rights: 
      - "Listen"
      - "Manage"
      - "Send"
