apiVersion: azure.microsoft.com/v1alpha1
kind: RedisCache
metadata:
  name: rediscache-sample-1
  labels: # Provide tags to add to RedisCache as labels
    tag1: value1
    tag2: value2
spec:
  location: westus
  resourceGroup: resourcegroup-azure-operators
  properties:
    # possible values for sku.Name are "Basic", "Premium" or "Standard"
    # possible values for sku.family are "C" and "P". 
    # If sku.Name is "Premium", then sku.family should be "P"
    sku:
      name: Basic
      family: C
      capacity: 1
    enableNonSslPort: true
    ## Optional - vnet usage may require a higher tier sku
    #subnetId: /subscriptions/{SUBID}/resourceGroups/{resourcegroupName}/providers/Microsoft.Network/virtualNetworks/{vnet name}/subnets/{subnet name}
    #staticIp: 172.22.0.10
  # Use the field below to optionally specify a different keyvault 
  # to store the primary and secondary key secrets in
  #keyVaultToStoreSecrets: asoSecretKeyVault