apiVersion: azure.microsoft.com/v1alpha1
kind: AzureSqlDatabase
metadata:
  name:  azuresqldatabase-sample
  labels: # Provide tags to add to AzureSqlDatabase as labels
    tag1: value1
    tag2: value2
spec:
  location: westus
  resourcegroup: resourcegroup-azure-operators
  server:  sqlserver-sample-777
  edition: 0
  # Optional
  # override metadata.name for database name
  # dbName: myDatabase
