apiVersion: azure.microsoft.com/v1alpha1
kind: AzureSqlAction
metadata:
  name: azuresqlaction-sample
spec:
  resourceGroup: resourcegroup-azure-operators
  serverName: sqlserver-sample-777
  
  # actionName: rolladmincreds
  ## Optionally specify the secretname and keyvault for the admin credentials secret
  # serverAdminSecretName: sqlserver-sample-777-secret
  # serverSecretKeyVault: asoSecretKeyVault

  # actionName: rollusercreds
  # dbName: azuresqldatabase-sample
  # dbUser: sqluser-sample
  ## Optionally specify the keyvault for the user credentials secret
  # userSecretKeyVault: asoSecretKeyVault