apiVersion: azure.microsoft.com/v1alpha1
kind: AzureSqlFailoverGroup
metadata:
  name: azuresqlfailovergroup-sample
spec:
  location: eastus
  resourceGroup: resourcegroup-azure-operators
  server: sqlserver-samplepri
  failoverpolicy: automatic
  failovergraceperiod: 30
  secondaryserver: sqlserver-samplesec
  secondaryserverresourcegroup: resourcegroup-azure-operators
  databaselist:
    - "azuresqldatabase-sample"
    - "azuresqldatabase-sample2"
  # Use the field below to optionally specify a different keyvault 
  # to store the listener endpoint secrets in
  #keyVaultToStoreSecrets: asoSecretKeyVault
