apiVersion: azure.microsoft.com/v1alpha1
kind: AzureSqlServer
metadata:
  name: sqlserver-sample777
  labels: # Provide tags to add to AzureSqlDatabase as labels
    tag1: value1
    tag2: value2
spec:
  location: westus
  resourcegroup: resourcegroup-azure-operators
  # Use the field below to optionally specify a different keyvault 
  # to store the server admin credential secrets in
  #keyVaultToStoreSecrets: asoSecretKeyVault
---
apiVersion: azure.microsoft.com/v1alpha1
kind: AzureSqlDatabase
metadata:
  name:  azuresqldatabase-sample
  labels: # Provide tags to add to AzureSqlDatabase as labels
    tag1: valueA
    tag2: valueB
spec:
  location: westus
  resourcegroup: resourcegroup-azure-operators
  server:  sqlserver-sample777
  edition: 0