apiVersion: azure.microsoft.com/v1alpha1
kind: AzureSqlServer
metadata:
  name: sqlserver-sample-777
  labels: # Provide tags to add to AzureSqlServer as labels
    tag1: value1
    tag2: value2
spec:
  location: westus
  resourceGroup: resourcegroup-azure-operators
  # Use the field below to optionally specify a different keyvault 
  # to store the server admin credential secrets in
  #keyVaultToStoreSecrets: asoSecretKeyVault