apiVersion: azure.microsoft.com/v1alpha1
kind: EventhubNamespace
metadata:
  name: eventhubnamespace-sample-1
spec:    
    location: "westus"
    resourceGroup: resourcegroup-azure-operators
    sku:
      name: "Standard"
      tier: "Standard"
      capacity: 1
    properties:
      isAutoInflateEnabled: false
      maximumThroughputUnits: 0
      kafkaEnabled: false
#networkRule is only supported on "Standard" tier namespace
    networkRule:
      defaultAction: deny
      virtualNetworkRules: 
        - subnetId: /subscriptions/{subscription_id}/resourceGroups/{resourcegroup}/providers/Microsoft.Network/virtualNetworks/{vnet_name}/subnets/{subnet_name}
          ignoreMissingServiceEndpoint: true
      ipRules:
        - ipMask: 1.1.1.1
        - ipMask: 2.2.0.0/24
