apiVersion: eventgrid.azure.com/v1beta20200601
kind: EventSubscription
metadata:
  name: sample-subscription
  namespace: default
spec:
  owner:
    name: sample-domain-topic
    group: microsoft.resources
    kind: ResourceGroup
  destination:
    storageQueue:
      endpointType: StorageQueue
      properties: 
        resourceReference: 
          group: storage.azure.com
          kind: StorageAccount
          name: samplekubestorage
        queueName: samplequeue
