apiVersion: eventgrid.azure.com/v1beta20200601
kind: EventSubscription
metadata:
  name: sample-subscription
  namespace: default
spec:
  owner:
    name: sample-domain-topic
    group: eventgrid.azure.com
    kind: Domain
  destination:
    storageQueue:
      endpointType: StorageQueue
      properties: 
        resourceReference: 
          group: storage.azure.com
          kind: StorageAccount
          name: samplekubestoragebeta
        queueName: samplequeuebeta
