apiVersion: dbforpostgresql.azure.com/v20250801
kind: FlexibleServersConfiguration
metadata:
  name: pgaudit
  namespace: default
spec:
  owner:
    name: asosampleserver20250801
  azureName: pgaudit.log
  source: user-override
  value: READ
