apiVersion: v1
name: azure-service-operator
version: 0.1.0
appVersion: 0.1.0
description: Deploy components and dependencies of azure-service-operator
home: https://github.com/Azure/azure-service-operator
sources:
  - https://github.com/Azure/azure-service-operator
dependencies:
  - name: aad-pod-identity
    version: 1.5.5
    repository: https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts
    condition: azureUseMI