apiVersion: compute.azure.com/v1beta20220301
kind: VirtualMachine
metadata:
  name: samplevm
  namespace: default
spec:
  location: westcentralus
  owner:
    name: aso-sample-rg
  hardwareProfile:
    vmSize: "Standard_A1_v2"
  storageProfile:
    imageReference:
      publisher: Canonical
      offer: UbuntuServer
      sku: 18.04-lts
      version: latest
  osProfile:
    computerNamePrefix: computer
    adminUsername: adminUser
    linuxConfiguration:
      disablePasswordAuthentication: true
      ssh:
        publicKeys:
          - keyData: ssh-rsa AAAAB  # Specify your SSH public key here
            path: /home/adminUser/.ssh/authorized_keys
  networkProfile:
    networkInterfaces:
      - reference:
          group: network.azure.com
          kind: NetworkInterface
          name: samplenic
