apiVersion: compute.azure.com/v1beta20200930
kind: Disk
metadata:
  name: sampledisk
  namespace: default
spec:
  location: westcentralus
  owner:
    name: aso-sample-rg
  sku:
    name: Standard_LRS
  creationData:
    createOption: Empty
  diskSizeGB: 500
