apiVersion: compute.azure.com/v1beta20220301
kind: Image
metadata:
  name: aso-sample-image
  namespace: default
spec:
  hyperVGeneration: "v2"
  location: westcentralus
  owner:
    name: aso-sample-rg
  storageProfile:
    osDisk:
      diskSizeGB: 32
      osType: linux
      osState: generalized
      snapshot:
        Reference:
          armID: aso-sample-snapshot

