# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/microsoft.resources.infra.azure.com_resourcegroups.yaml
- bases/microsoft.network.infra.azure.com_virtualnetworks.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
- patches/webhook_in_resourcegroups.yaml
- patches/webhook_in_virtualnetworks.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

- patches/cainjection_in_resourcegroups.yaml
- patches/cainjection_in_virtualnetworks.yaml

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
