# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/azure.microsoft.com_storages.yaml
- bases/azure.microsoft.com_cosmosdbs.yaml
- bases/azure.microsoft.com_rediscaches.yaml
- bases/azure.microsoft.com_eventhubs.yaml
- bases/azure.microsoft.com_resourcegroups.yaml
- bases/azure.microsoft.com_eventhubnamespaces.yaml
- bases/azure.microsoft.com_consumergroups.yaml
- bases/azure.microsoft.com_keyvaults.yaml
- bases/azure.microsoft.com_sqlservers.yaml
- bases/azure.microsoft.com_sqldatabases.yaml
- bases/azure.microsoft.com_sqlfirewallrules.yaml
- bases/azure.microsoft.com_sqlactions.yaml
- bases/azure.microsoft.com_azuredatalakegen2filesystems.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_eventhubs.yaml
#- patches/webhook_in_resourcegroups.yaml
#- patches/webhook_in_eventhubnamespaces.yaml
#- patches/webhook_in_consumergroups.yaml
#- patches/webhook_in_keyvaults.yaml
#- patches/webhook_in_sqlservers.yaml
#- patches/webhook_in_sqldatabases.yaml
#- patches/webhook_in_sqlfirewallrules.yaml
#- patches/webhook_in_sqlactions.yaml
#- patches/webhook_in_azuredatalakegen2filesystems.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CAINJECTION] patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_eventhubs.yaml
#- patches/cainjection_in_resourcegroups.yaml
#- patches/cainjection_in_eventhubnamespaces.yaml
#- patches/cainjection_in_consumergroups.yaml
#- patches/cainjection_in_keyvaults.yaml
#- patches/cainjection_in_sqlservers.yaml
#- patches/cainjection_in_sqldatabases.yaml
#- patches/cainjection_in_sqlfirewallrules.yaml
#- patches/cainjection_in_sqlactions.yaml
#- patches/cainjection_in_azuredatalakegen2filesystems.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
