# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/azure.microsoft.com_storages.yaml
- bases/azure.microsoft.com_cosmosdbs.yaml
- bases/azure.microsoft.com_rediscaches.yaml
- bases/azure.microsoft.com_eventhubs.yaml
- bases/azure.microsoft.com_resourcegroups.yaml
- bases/azure.microsoft.com_eventhubnamespaces.yaml
- bases/azure.microsoft.com_consumergroups.yaml
- bases/azure.microsoft.com_keyvaults.yaml
- bases/azure.microsoft.com_azuresqlservers.yaml
- bases/azure.microsoft.com_azuresqldatabases.yaml
- bases/azure.microsoft.com_azuresqlfirewallrules.yaml
- bases/azure.microsoft.com_azuresqlactions.yaml
- bases/azure.microsoft.com_azuresqlfailovergroups.yaml
- bases/azure.microsoft.com_blobcontainers.yaml
- bases/azure.microsoft.com_azuredatalakegen2filesystems.yaml
- bases/azure.microsoft.com_postgresqlservers.yaml
- bases/azure.microsoft.com_postgresqldatabases.yaml
- bases/azure.microsoft.com_postgresqlfirewallrules.yaml
- bases/azure.microsoft.com_apimservices.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_eventhubs.yaml
#- patches/webhook_in_resourcegroups.yaml
#- patches/webhook_in_eventhubnamespaces.yaml
#- patches/webhook_in_consumergroups.yaml
#- patches/webhook_in_keyvaults.yaml
#- patches/webhook_in_azuresqlservers.yaml
#- patches/webhook_in_azuresqldatabases.yaml
#- patches/webhook_in_azuresqlfirewallrules.yaml
#- patches/webhook_in_azuresqlactions.yaml
#- patches/webhook_in_azuresqlfailovergroups.yaml
#- patches/webhook_in_blobcontainers.yaml
#- patches/webhook_in_azuredatalakegen2filesystems.yaml
#- patches/webhook_in_postgresqlservers.yaml
#- patches/webhook_in_postgresqldatabases.yaml
#- patches/webhook_in_postgresqlfirewallrules.yaml
#- patches/webhook_in_apimservices.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CAINJECTION] patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_eventhubs.yaml
#- patches/cainjection_in_resourcegroups.yaml
#- patches/cainjection_in_eventhubnamespaces.yaml
#- patches/cainjection_in_consumergroups.yaml
#- patches/cainjection_in_keyvaults.yaml
#- patches/cainjection_in_azuresqlservers.yaml
#- patches/cainjection_in_azuresqldatabases.yaml
#- patches/cainjection_in_azuresqlfirewallrules.yaml
#- patches/cainjection_in_azuresqlactions.yaml
#- patches/cainjection_in_azuresqlfailovergroups.yaml
#- patches/cainjection_in_blobcontainers.yaml
#- patches/cainjection_in_azuredatalakegen2filesystems.yaml
#- patches/cainjection_in_postgresqlservers.yaml
#- patches/cainjection_in_postgresqldatabases.yaml
#- patches/cainjection_in_postgresqlfirewallrules.yaml
#- patches/cainjection_in_apimservices.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
