apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: mysqlaadusers.azure.microsoft.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.provisioned
    name: Provisioned
    type: string
  - JSONPath: .status.message
    name: Message
    type: string
  group: azure.microsoft.com
  names:
    kind: MySQLAADUser
    listKind: MySQLAADUserList
    plural: mysqlaadusers
    singular: mysqlaaduser
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: MySQLAADUser is the Schema for an AAD user for MySQL
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MySQLAADUserSpec defines the desired state of MySQLAADUser
          properties:
            aadId:
              description: AAD ID is the ID of the user in Azure Active Directory. When creating a user for a managed identity this must be the client id (sometimes called app id) of the managed identity. When creating a user for a "normal" (non-managed identity) user or group, this is the OID of the user or group.
              type: string
            dbName:
              type: string
            resourceGroup:
              pattern: ^[-\w\._\(\)]+$
              type: string
            roles:
              description: The roles assigned to the user. A user must have at least one role.
              items:
                type: string
              type: array
            server:
              type: string
            username:
              description: optional
              type: string
          required:
          - dbName
          - resourceGroup
          - roles
          - server
          type: object
        status:
          description: ASOStatus (AzureServiceOperatorsStatus) defines the observed state of resource actions
          properties:
            completed:
              format: date-time
              type: string
            containsUpdate:
              type: boolean
            failedProvisioning:
              type: boolean
            flattenedSecrets:
              type: boolean
            message:
              type: string
            output:
              type: string
            pollingUrl:
              type: string
            provisioned:
              type: boolean
            provisioning:
              type: boolean
            requested:
              format: date-time
              type: string
            resourceId:
              type: string
            specHash:
              type: string
            state:
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
