apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: azuresqlvnetrules.azure.microsoft.com
spec:
  group: azure.microsoft.com
  names:
    kind: AzureSQLVNetRule
    listKind: AzureSQLVNetRuleList
    plural: azuresqlvnetrules
    shortNames:
    - asqlvnr
    singular: azuresqlvnetrule
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.provisioned
      name: Provisioned
      type: string
    - jsonPath: .status.message
      name: Message
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: AzureSQLVNetRule is the Schema for the azuresqlvnetrules API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: 'NOTE: json tags are required.  Any new fields you add must
              have json tags for the fields to be serialized. AzureSQLVNetRuleSpec
              defines the desired state of AzureSQLVNetRule'
            properties:
              ignoreMissingServiceEndpoint:
                type: boolean
              resourceGroup:
                description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                  Important: Run "make" to regenerate code after modifying this file'
                minLength: 1
                pattern: ^[-\w\._\(\)]+$
                type: string
              server:
                minLength: 1
                type: string
              subnetName:
                type: string
              vNetName:
                type: string
              vNetResourceGroup:
                type: string
              vNetSubscriptionID:
                type: string
            required:
            - resourceGroup
            - server
            - subnetName
            - vNetName
            - vNetResourceGroup
            type: object
          status:
            description: ASOStatus (AzureServiceOperatorsStatus) defines the observed
              state of resource actions
            properties:
              completed:
                format: date-time
                type: string
              containsUpdate:
                type: boolean
              failedProvisioning:
                type: boolean
              flattenedSecrets:
                type: boolean
              message:
                type: string
              output:
                type: string
              pollingUrl:
                type: string
              pollingUrlKind:
                enum:
                - CreateOrUpdate
                - Delete
                type: string
              provisioned:
                type: boolean
              provisioning:
                type: boolean
              requested:
                format: date-time
                type: string
              resourceId:
                type: string
              specHash:
                type: string
              state:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
