apiVersion: microsoft.documentdb.azure.com/v1alpha1api20210515
kind: DatabaseAccount
metadata:
  name: sample-sqldb-account
  namespace: default
spec:
  location: westcentralus
  owner:
    name: aso-sample-rg
  kind: GlobalDocumentDB
  databaseAccountOfferType: Standard
  locations:
    - locationName: westcentralus
