apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: azure-service-operator-v1
    control-plane: controller-manager
  name: azureoperator-controller-manager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        aadpodidbinding: aso_manager_binding
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --metrics-addr=127.0.0.1:8080
        command:
        - /manager
        env:
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: AZURE_CLIENT_ID
              name: azureoperatorsettings
              optional: true
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: AZURE_CLIENT_SECRET
              name: azureoperatorsettings
              optional: true
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              key: AZURE_TENANT_ID
              name: azureoperatorsettings
              optional: true
        - name: AZURE_SUBSCRIPTION_ID
          valueFrom:
            secretKeyRef:
              key: AZURE_SUBSCRIPTION_ID
              name: azureoperatorsettings
              optional: true
        - name: AZURE_USE_MI
          valueFrom:
            secretKeyRef:
              key: AZURE_USE_MI
              name: azureoperatorsettings
              optional: true
        - name: AZURE_OPERATOR_KEYVAULT
          valueFrom:
            secretKeyRef:
              key: AZURE_OPERATOR_KEYVAULT
              name: azureoperatorsettings
              optional: true
        - name: AZURE_CLOUD_ENV
          valueFrom:
            secretKeyRef:
              key: AZURE_CLOUD_ENV
              name: azureoperatorsettings
              optional: true
        - name: AZURE_SECRET_NAMING_VERSION
          valueFrom:
            secretKeyRef:
              key: AZURE_SECRET_NAMING_VERSION
              name: azureoperatorsettings
              optional: true
        - name: PURGE_DELETED_KEYVAULT_SECRETS
          valueFrom:
            secretKeyRef:
              key: PURGE_DELETED_KEYVAULT_SECRETS
              name: azureoperatorsettings
              optional: true
        - name: RECOVER_SOFT_DELETED_KEYVAULT_SECRETS
          valueFrom:
            secretKeyRef:
              key: RECOVER_SOFT_DELETED_KEYVAULT_SECRETS
              name: azureoperatorsettings
              optional: true
        - name: AZURE_TARGET_NAMESPACES
          valueFrom:
            secretKeyRef:
              key: AZURE_TARGET_NAMESPACES
              name: azureoperatorsettings
              optional: true
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: REQUEUE_AFTER
          value: "30"
        image: {{ .Values.image.repository }}
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 8081
          name: liveness-port
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: {{ .Values.image.kubeRBACProxy }}
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      nodeSelector:
        kubernetes.io/os: linux
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
