name: Render Visualizations of Azure Service Operator components
on:
  workflow_dispatch:
    # no content, allows manual triggering

  schedule:
    # 5:30 pm every Sunday (UTC)
    # to ensure the images are never too stale
    - cron: '30 17 * * 0'
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Update ASO v1 diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github,v2"
          output_file: "docs/hugo/static/images/aso-v1-structure.svg"
          commit_message: "Updating visualization for ASO v1"

      - name: Update ASO v2 diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github,v2/tools"
          output_file: "docs/hugo/static/images/aso-v2-structure.svg"
          root_path: "v2"
          commit_message: "Updating visualization for ASO v2"

      - name: Update ASO Codegen diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github"
          output_file: "docs/hubo/static/images/aso-codegen-structure.svg"
          root_path: "v2/tools"
          commit_message: "Updating visualization for the code generator"

      - name: Create Pull Request
        uses: actions/checkout@v
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update Code Structure Diagrams
          branch: bot/update-diagrams
          delete-branch: true
          title: '[Automated] Update Code Structure Diagrams'
          body: |
            Update visualisation diagrams showing the structure of ASO code
            
            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            automated pr
