name: Render Source Visualizations
on:
  workflow_dispatch:
    # no content, allows manual triggering

  schedule:
    # 5:35 pm every Sunday (UTC)
    # to ensure the images are never too stale
    - cron: "35 17 * * 0"
jobs:
  render:
    
    runs-on: ubuntu-latest

    permissions:
      contents: read

    # Only run this scheduled job on the main repo, it can't work elsewhere
    if: ${{ github.repository == 'Azure/azure-service-operator' }}

    steps:
      - name: Create token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          # required
          app-id: ${{ secrets.AUTOMATION_ID }}
          private-key: ${{ secrets.AUTOMATION_KEY }}
          
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pinned to 4.1.7
        with:
          ref: main

      - name: Create Branch
        uses: peterjgrainger/action-create-branch@10c7d268152480ae859347db45dc69086cef1d9c # pinned to v3.0.0
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          branch: "bot/update-diagrams"

      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pinned to 4.1.7
        with:
          ref: bot/update-diagrams

      - name: Update ASO v2 diagram
        uses: githubocto/repo-visualizer@main
        with:
          # Paths are relative to root_path
          excluded_paths: "ignore,.github,tools,cmd"
          output_file: "docs/hugo/content/contributing/aso-v2-structure.svg"
          root_path: "v2"
          commit_message: "Updating visualization for ASO v2"
          should_push: false

      - name: Update asoctl diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github"
          output_file: "docs/hugo/content/contributing/asoctl-structure.svg"
          root_path: "v2/cmd/asoctl"
          commit_message: "Updating visualization for asoctl"
          should_push: false

      - name: Update ASO Code Generator diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github"
          output_file: "docs/hugo/content/contributing/aso-codegen-structure.svg"
          root_path: "v2/tools/generator"
          commit_message: "Updating visualization for the code generator"
          should_push: false

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # pinned to v7.0.5
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: Update Code Structure Diagrams
          branch: bot/update-diagrams
          base: main
          delete-branch: true
          title: "[Automated] Update Code Structure Diagrams"
          body: |
            Update visualisation diagrams showing the structure of ASO code

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            automated pr
