name: Render Visualizations of Azure Service Operator components
on:
  workflow_dispatch:
    # no content, allows manual triggering

  schedule:
    # 5:30 pm every Sunday (UTC)
    # to ensure the images are never too stale
    - cron: '30 17 * * 0'
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Create Branch
        uses: peterjgrainger/action-create-branch@b48b0ca0e307c9b56f059b70274984ffeaa90a43 # Pinned to v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          branch: 'bot/update-diagrams'

      - name: Checkout code
        uses: actions/checkout@master
        with:
            ref: bot/update-diagrams

      - name: Update ASO v1 diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github,v2"
          output_file: "docs/hugo/content/contributing/contributing/aso-v1-structure.svg"
          commit_message: "Updating visualization for ASO v1"
          should_push: false

      - name: Update ASO v2 diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github,tools"
          output_file: "docs/hugo/content/contributing/contributing/aso-v2-structure.svg"
          root_path: "v2"
          commit_message: "Updating visualization for ASO v2"
          should_push: false

      - name: Update ASO Codegen diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github"
          output_file: "docs/hugo/content/contributing/contributing/aso-codegen-structure.svg"
          root_path: "v2/tools"
          commit_message: "Updating visualization for the code generator"
          should_push: false

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@7380612b49221684fefa025244f2ef4008ae50ad # v3.10.1
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: Update Code Structure Diagrams
          branch: bot/update-diagrams
          base: main
          delete-branch: true
          title: '[Automated] Update Code Structure Diagrams'
          body: |
            Update visualisation diagrams showing the structure of ASO code
            
            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            automated pr
